-- 1. Total number of different drivers for each customer

SELECT CUSTOMER_ID, COUNT(DISTINCT DRIVER_ID) AS NUMBER_OF_DRIVERS
FROM TBL_BOOKINGS
GROUP BY CUSTOMER_ID;

-- 2. Total rides taken by each customer

SELECT CUSTOMER_ID, COUNT(BOOKING_ID) AS NUMBER_OF_RIDES
FROM TBL_BOOKINGS
GROUP BY CUSTOMER_ID;

-- 3. Conversion ratio

SELECT
    (
        SUM(CASE WHEN BUTTON_ID='fcba68aa-1231-11eb-adc1-0242ac120002' AND IS_BUTTON_CLICK='Yes' THEN 1 ELSE 0 END)
        /
        SUM(CASE WHEN PAGE_ID='e7bc5fb2-1231-11eb-adc1-0242ac120002' AND IS_PAGE_VIEW='Yes' THEN 1 ELSE 0 END)
    ) AS CONVERSION_RATIO
FROM TBL_CLICK_STREAMS;

-- 4. Total trips done by black coloured cabs

SELECT COUNT(CAB_REGISTRATION_NO) AS TOTAL_TRIPS_BY_BLACK_COLOURED_CAB
FROM TBL_BOOKINGS
WHERE CAB_COLOR='black'
GROUP BY CAB_COLOR;

-- 5. Date wise total amount of tips given

SELECT TRIP_DATE, TOTAL_TIP_AMOUNT
FROM TBL_AGGREGATED_BOOKINGS;

-- 6. Total count of bookings with ratings lower than 2 as given by customers in a particular month

SELECT DATE_FORMAT(PICKUP_TIMESTAMP,'yyyy-MM') AS `MONTH`, COUNT(BOOKING_ID) AS LOW_RATED_TRIPS_IN_A_MONTH
FROM TBL_BOOKINGS
WHERE RATING_BY_CUSTOMER < 2
GROUP BY (DATE_FORMAT(PICKUP_TIMESTAMP,'yyyy-MM'))
ORDER BY `MONTH`;

-- 7. Total iOS users

SELECT COUNT(DISTINCT CUSTOMER_ID) AS TOTAL_IOS_USERS
FROM TBL_CLICK_STREAMS
WHERE OS_VERSION='iOS';
